markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: wanghongjun2014
author: "王洪军"
email: wanghongjun2014#163.com
name: "王洪军个人博客"
url: https://wanghongjun2014.github.io
domain: wanghongjun2014.github.io
all_categories: [
["code", "技术","/posts/code.html"],
["lift", "生活","/posts/life.html"],
["about", "关于","/about.html"],
["smallcode", "一些实用的小程序", "/smallcode.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
